"""Initial database setup

Revision ID: 2014fe04a7bd
Revises: 5fb0d42ba0e5
Create Date: 2025-09-06 11:23:44.887561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2014fe04a7bd'
down_revision = '5fb0d42ba0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('image_file')
        batch_op.drop_column('category')
        batch_op.drop_column('selling_price')
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('selling_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_file', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
