"""Remove customer_city column from bill table

Revision ID: 4428d6a86493
Revises: 2014fe04a7bd
Create Date: 2025-11-16 21:32:41.480975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4428d6a86493'
down_revision = '2014fe04a7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
    
    # Remove customer_city column from bill table if it exists
    # Check if column exists first to avoid errors
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('bill')]
    
    if 'customer_city' in columns:
        with op.batch_alter_table('bill', schema=None) as batch_op:
            batch_op.drop_column('customer_city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
    
    # Add customer_city column back if needed (for rollback)
    # Note: This is optional since the model doesn't use it
    # with op.batch_alter_table('bill', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('customer_city', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###
