"""Add cost_price, selling_price, and image_file to product table

Revision ID: 5fb0d42ba0e5
Revises: 1b279e621d98
Create Date: 2025-09-05 22:54:10.936838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fb0d42ba0e5'
down_revision = '1b279e621d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('image_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('category')
        batch_op.drop_column('image_file')
        batch_op.drop_column('selling_price')
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###
